version: '3'
# microservices
services:
   postgres: # service name
    image: postgres:13 # image from the docker hub
    container_name: postgres_db #default name of the container.
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" # host:docker
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    networks:
      - airflow_network # this need to assined in all the services we define here to have communication between the services
    
networks:
  airflow_network:
    external: false  # creates the airflow network if it doesn't exists.

volumes:
   postgres_data:  # creates the volumes if it doesn't exists.

